import { NavigationItem } from '@ojiepermana/angular/navigation';

export const AppNavigation: NavigationItem[] = [
  {
    id: 'shadn-ui',
    title: 'Shadn UI',
    subtitle: 'shadcn components and chart demos',
    type: 'group',
    icon: 'deployed_code',
    children: [
      {
        id: 'shadn-ui-component',
        title: 'Component',
        type: 'collapsable',
        icon: 'deployed_code',
        children: [
          {
            id: 'shadcn-accordion',
            title: 'Accordion',
            type: 'basic',
            icon: 'expand_more',
            link: '/ui/shadcn/accordion',
          },
          { id: 'shadcn-alert', title: 'Alert', type: 'basic', icon: 'error_outline', link: '/ui/shadcn/alert' },
          { id: 'shadcn-avatar', title: 'Avatar', type: 'basic', icon: 'account_circle', link: '/ui/shadcn/avatar' },
          { id: 'shadcn-badge', title: 'Badge', type: 'basic', icon: 'verified', link: '/ui/shadcn/badge' },
          {
            id: 'shadcn-breadcrumb',
            title: 'Breadcrumb',
            type: 'basic',
            icon: 'more_horiz',
            link: '/ui/shadcn/breadcrumb',
          },
          { id: 'shadcn-button', title: 'Button', type: 'basic', icon: 'crop_square', link: '/ui/shadcn/button' },
          {
            id: 'shadcn-calendar',
            title: 'Calendar',
            type: 'basic',
            icon: 'calendar_month',
            link: '/ui/shadcn/calendar',
          },
          { id: 'shadcn-card', title: 'Card', type: 'basic', icon: 'credit_card', link: '/ui/shadcn/card' },
          { id: 'shadcn-checkbox', title: 'Checkbox', type: 'basic', icon: 'check_box', link: '/ui/shadcn/checkbox' },
          { id: 'shadcn-combobox', title: 'Combobox', type: 'basic', icon: 'search', link: '/ui/shadcn/combobox' },
          {
            id: 'shadcn-command',
            title: 'Command',
            type: 'basic',
            icon: 'keyboard_command_key',
            link: '/ui/shadcn/command',
          },
          {
            id: 'shadcn-context-menu',
            title: 'Context Menu',
            type: 'basic',
            icon: 'more_vert',
            link: '/ui/shadcn/context-menu',
          },
          {
            id: 'shadcn-date-picker',
            title: 'Date Picker',
            type: 'basic',
            icon: 'event',
            link: '/ui/shadcn/date-picker',
          },
          { id: 'shadcn-dialog', title: 'Dialog', type: 'basic', icon: 'chat', link: '/ui/shadcn/dialog' },
          {
            id: 'shadcn-dropdown-menu',
            title: 'Dropdown Menu',
            type: 'basic',
            icon: 'menu_open',
            link: '/ui/shadcn/dropdown-menu',
          },
          { id: 'shadcn-form', title: 'Form', type: 'basic', icon: 'description', link: '/ui/shadcn/form' },
          { id: 'shadcn-input', title: 'Input', type: 'basic', icon: 'text_fields', link: '/ui/shadcn/input' },
          { id: 'shadcn-label', title: 'Label', type: 'basic', icon: 'label', link: '/ui/shadcn/label' },
          {
            id: 'shadcn-pagination',
            title: 'Pagination',
            type: 'basic',
            icon: 'first_page',
            link: '/ui/shadcn/pagination',
          },
          { id: 'shadcn-popover', title: 'Popover', type: 'basic', icon: 'bubble_chart', link: '/ui/shadcn/popover' },
          {
            id: 'shadcn-progress',
            title: 'Progress',
            type: 'basic',
            icon: 'hourglass_empty',
            link: '/ui/shadcn/progress',
          },
          { id: 'shadcn-radio', title: 'Radio', type: 'basic', icon: 'radio_button_checked', link: '/ui/shadcn/radio' },
          {
            id: 'shadcn-scroll-area',
            title: 'Scroll Area',
            type: 'basic',
            icon: 'swap_vert',
            link: '/ui/shadcn/scroll-area',
          },
          { id: 'shadcn-select', title: 'Select', type: 'basic', icon: 'expand_more', link: '/ui/shadcn/select' },
          { id: 'shadcn-separator', title: 'Separator', type: 'basic', icon: 'remove', link: '/ui/shadcn/separator' },
          { id: 'shadcn-sheet', title: 'Sheet', type: 'basic', icon: 'view_sidebar', link: '/ui/shadcn/sheet' },
          { id: 'shadcn-skeleton', title: 'Skeleton', type: 'basic', icon: 'view_agenda', link: '/ui/shadcn/skeleton' },
          { id: 'shadcn-slider', title: 'Slider', type: 'basic', icon: 'tune', link: '/ui/shadcn/slider' },
          { id: 'shadcn-switch', title: 'Switch', type: 'basic', icon: 'toggle_on', link: '/ui/shadcn/switch' },
          { id: 'shadcn-table', title: 'Table', type: 'basic', icon: 'table_chart', link: '/ui/shadcn/table' },
          { id: 'shadcn-tabs', title: 'Tabs', type: 'basic', icon: 'tab', link: '/ui/shadcn/tabs' },
          { id: 'shadcn-textarea', title: 'Textarea', type: 'basic', icon: 'notes', link: '/ui/shadcn/textarea' },
          { id: 'shadcn-toast', title: 'Toast', type: 'basic', icon: 'notifications', link: '/ui/shadcn/toast' },
          { id: 'shadcn-tooltip', title: 'Tooltip', type: 'basic', icon: 'help', link: '/ui/shadcn/tooltip' },
        ],
      },
      {
        id: 'shadn-ui-chart',
        title: 'Chart',
        type: 'collapsable',
        icon: 'monitoring',
        children: [
          {
            id: 'shadn-ui-chart-bar',
            title: 'Bar',
            type: 'basic',
            icon: 'bar_chart',
            link: '/ui/chart/bar',
            exactMatch: true,
          },
          {
            id: 'shadn-ui-chart-line',
            title: 'Line',
            type: 'basic',
            icon: 'show_chart',
            link: '/ui/chart/line',
            exactMatch: true,
          },
          {
            id: 'shadn-ui-chart-area',
            title: 'Area',
            type: 'basic',
            icon: 'area_chart',
            link: '/ui/chart/area',
            exactMatch: true,
          },
          {
            id: 'shadn-ui-chart-pie',
            title: 'Pie',
            type: 'basic',
            icon: 'pie_chart',
            link: '/ui/chart/pie',
            exactMatch: true,
          },
          {
            id: 'shadn-ui-chart-radar',
            title: 'Radar',
            type: 'basic',
            icon: 'radar',
            link: '/ui/chart/radar',
            exactMatch: true,
          },
          {
            id: 'shadn-ui-chart-radial',
            title: 'Radial',
            type: 'basic',
            icon: 'donut_large',
            link: '/ui/chart/radial',
            exactMatch: true,
          },
          {
            id: 'shadn-ui-chart-scatter',
            title: 'Scatter',
            type: 'basic',
            icon: 'scatter_plot',
            link: '/ui/chart/scatter',
            exactMatch: true,
          },
          {
            id: 'shadn-ui-chart-tooltip',
            title: 'Tooltip',
            type: 'basic',
            icon: 'info',
            link: '/ui/chart/tooltip',
            exactMatch: true,
          },
        ],
      },
    ],
  },
  {
    id: 'angular-material',
    title: 'Angular Material',
    subtitle: 'Material component demos from the library',
    type: 'group',
    icon: 'dashboard_customize',
    children: [
      {
        id: 'user-interface-material-components-inputs-forms',
        title: 'Inputs & Forms',
        type: 'collapsable',
        icon: 'input',
        children: [
          {
            id: 'user-interface-material-components-inputs-forms-autocomplete',
            title: 'Autocomplete',
            type: 'basic',
            icon: 'search',
            link: '/ui/material/autocomplete',
          },
          {
            id: 'user-interface-material-components-inputs-forms-checkbox',
            title: 'Checkbox',
            type: 'basic',
            icon: 'check_box',
            link: '/ui/material/checkbox',
          },
          {
            id: 'user-interface-material-components-inputs-forms-datepicker',
            title: 'Datepicker',
            type: 'basic',
            icon: 'calendar_today',
            link: '/ui/material/datepicker',
          },
          {
            id: 'user-interface-material-components-inputs-forms-form-field',
            title: 'Form field',
            type: 'basic',
            icon: 'text_fields',
            link: '/ui/material/form-field',
          },
          {
            id: 'user-interface-material-components-inputs-forms-input',
            title: 'Input',
            type: 'basic',
            icon: 'text_fields',
            link: '/ui/material/input',
          },
          {
            id: 'user-interface-material-components-inputs-forms-radio-button',
            title: 'Radio button',
            type: 'basic',
            icon: 'radio_button_checked',
            link: '/ui/material/radio',
          },
          {
            id: 'user-interface-material-components-inputs-forms-select',
            title: 'Select',
            type: 'basic',
            icon: 'expand_more',
            link: '/ui/material/select',
          },
          {
            id: 'user-interface-material-components-inputs-forms-slider',
            title: 'Slider',
            type: 'basic',
            icon: 'tune',
            link: '/ui/material/slider',
          },
          {
            id: 'user-interface-material-components-inputs-forms-slide-toggle',
            title: 'Slide toggle',
            type: 'basic',
            icon: 'toggle_on',
            link: '/ui/material/slide-toggle',
          },
        ],
      },
      {
        id: 'user-interface-material-components-buttons-actions',
        title: 'Buttons & Actions',
        type: 'collapsable',
        icon: 'ads_click',
        children: [
          {
            id: 'user-interface-material-components-buttons-actions-button',
            title: 'Button',
            type: 'basic',
            icon: 'crop_square',
            link: '/ui/material/button',
          },
          {
            id: 'user-interface-material-components-buttons-actions-button-toggle',
            title: 'Button toggle',
            type: 'basic',
            icon: 'view_column',
            link: '/ui/material/button-toggle',
          },
          {
            id: 'user-interface-material-components-buttons-actions-chips',
            title: 'Chips',
            type: 'basic',
            icon: 'label',
            link: '/ui/material/chips',
            badge: {
              title: 'New',
              classes: 'ml-2 px-2 py-0.5 rounded-full text-xs bg-green-500 text-white',
            },
          },
          {
            id: 'user-interface-material-components-buttons-actions-menu',
            title: 'Menu',
            type: 'basic',
            icon: 'menu',
            link: '/ui/material/menu',
          },
          {
            id: 'user-interface-material-components-buttons-actions-ripples',
            title: 'Ripples',
            type: 'basic',
            icon: 'waves',
            link: '/ui/material/ripples',
          },
        ],
      },
      {
        id: 'user-interface-material-components-layout-containers',
        title: 'Layout & Containers',
        type: 'collapsable',
        icon: 'dashboard',
        children: [
          {
            id: 'user-interface-material-components-layout-containers-card',
            title: 'Card',
            type: 'basic',
            icon: 'credit_card',
            link: '/ui/material/card',
          },
          {
            id: 'user-interface-material-components-layout-containers-divider',
            title: 'Divider',
            type: 'basic',
            icon: 'remove',
            link: '/ui/material/divider',
          },
          {
            id: 'user-interface-material-components-layout-containers-expansion-panel',
            title: 'Expansion Panel',
            type: 'basic',
            icon: 'expand_more',
            link: '/ui/material/expansion',
          },
          {
            id: 'user-interface-material-components-layout-containers-grid-list',
            title: 'Grid list',
            type: 'basic',
            icon: 'grid_view',
            link: '/ui/material/grid-list',
          },
          {
            id: 'user-interface-material-components-layout-containers-list',
            title: 'List',
            type: 'basic',
            icon: 'list',
            link: '/ui/material/list',
          },
          {
            id: 'user-interface-material-components-layout-containers-sidenav',
            title: 'Sidenav',
            type: 'basic',
            icon: 'view_sidebar',
            link: '/ui/material/sidenav',
          },
          {
            id: 'user-interface-material-components-layout-containers-tabs',
            title: 'Tabs',
            type: 'basic',
            icon: 'tab',
            link: '/ui/material/tabs',
          },
          {
            id: 'user-interface-material-components-layout-containers-toolbar',
            title: 'Toolbar',
            type: 'basic',
            icon: 'build',
            link: '/ui/material/toolbar',
          },
        ],
      },
      {
        id: 'user-interface-material-components-data-display',
        title: 'Data & Display',
        type: 'collapsable',
        icon: 'bar_chart',
        children: [
          {
            id: 'user-interface-material-components-data-display-badge',
            title: 'Badge',
            type: 'basic',
            icon: 'verified',
            link: '/ui/material/badge',
          },
          {
            id: 'user-interface-material-components-data-display-icon',
            title: 'Icon',
            type: 'basic',
            icon: 'star',
            link: '/ui/material/icon',
          },
          {
            id: 'user-interface-material-components-data-display-paginator',
            title: 'Paginator',
            type: 'basic',
            icon: 'first_page',
            link: '/ui/material/paginator',
          },
          {
            id: 'user-interface-material-components-data-display-progress-bar',
            title: 'Progress bar',
            type: 'basic',
            icon: 'hourglass_empty',
            link: '/ui/material/progress-bar',
          },
          {
            id: 'user-interface-material-components-data-display-progress-spinner',
            title: 'Progress spinner',
            type: 'basic',
            icon: 'progress_activity',
            link: '/ui/material/progress-spinner',
          },
          {
            id: 'user-interface-material-components-data-display-sort',
            title: 'Sort header',
            type: 'basic',
            icon: 'swap_vert',
            link: '/ui/material/sort',
          },
          {
            id: 'user-interface-material-components-data-display-table',
            title: 'Table',
            type: 'basic',
            icon: 'table_chart',
            link: '/ui/material/table',
          },
          {
            id: 'user-interface-material-components-data-display-tree',
            title: 'Tree',
            type: 'basic',
            icon: 'hub',
            link: '/ui/material/tree',
          },
        ],
      },
      {
        id: 'user-interface-material-components-overlays-modals',
        title: 'Overlays & Modals',
        type: 'collapsable',
        icon: 'layers',
        children: [
          {
            id: 'user-interface-material-components-overlays-modals-bottom-sheet',
            title: 'Bottom Sheet',
            type: 'basic',
            icon: 'south',
            link: '/ui/material/bottom-sheet',
          },
          {
            id: 'user-interface-material-components-overlays-modals-dialog',
            title: 'Dialog',
            type: 'basic',
            icon: 'chat',
            link: '/ui/material/dialog',
          },
          {
            id: 'user-interface-material-components-overlays-modals-snack-bar',
            title: 'Snack-bar',
            type: 'basic',
            icon: 'notifications',
            link: '/ui/material/snack-bar',
          },
          {
            id: 'user-interface-material-components-overlays-modals-tooltip',
            title: 'Tooltip',
            type: 'basic',
            icon: 'help',
            link: '/ui/material/tooltip',
          },
        ],
      },
      {
        id: 'user-interface-material-components-navigation-stepper',
        title: 'Navigation & Steps',
        type: 'collapsable',
        icon: 'account_tree',
        children: [
          {
            id: 'user-interface-material-components-navigation-stepper-stepper',
            title: 'Stepper',
            type: 'basic',
            icon: 'account_tree',
            link: '/ui/material/stepper',
          },
        ],
      },
    ],
  },
  {
    id: 'angular-cdk',
    title: 'Angular CDK',
    subtitle: 'CDK utilities and primitives from the library',
    type: 'group',
    icon: 'widgets',
    children: [
      {
        id: 'user-interface-angular-cdk-accessibility-navigation',
        title: 'Accessibility & Navigation',
        type: 'collapsable',
        icon: 'accessibility',
        children: [
          {
            id: 'user-interface-angular-cdk-accessibility-navigation-a11y',
            title: 'Accessibility',
            type: 'basic',
            icon: 'accessibility',
            link: '/ui/cdk/a11y',
          },
          {
            id: 'user-interface-angular-cdk-accessibility-navigation-focus-trap',
            title: 'Focus Trap',
            type: 'basic',
            icon: 'center_focus_strong',
            link: '/ui/cdk/focus-trap',
          },
          {
            id: 'user-interface-angular-cdk-accessibility-navigation-live-announcer',
            title: 'Live Announcer',
            type: 'basic',
            icon: 'campaign',
            link: '/ui/cdk/live-announcer',
          },
          {
            id: 'user-interface-angular-cdk-accessibility-navigation-listbox',
            title: 'Listbox',
            type: 'basic',
            icon: 'list',
            link: '/ui/cdk/listbox',
          },
          {
            id: 'user-interface-angular-cdk-accessibility-navigation-menu-cdk',
            title: 'Menu',
            type: 'basic',
            icon: 'menu',
            link: '/ui/cdk/menu',
          },
        ],
      },
      {
        id: 'user-interface-angular-cdk-layout-positioning',
        title: 'Layout & Positioning',
        type: 'collapsable',
        icon: 'dashboard',
        children: [
          {
            id: 'user-interface-angular-cdk-layout-positioning-layout',
            title: 'Layout',
            type: 'basic',
            icon: 'dashboard',
            link: '/ui/cdk/layout',
          },
          {
            id: 'user-interface-angular-cdk-layout-positioning-overlay',
            title: 'Overlay',
            type: 'basic',
            icon: 'layers',
            link: '/ui/cdk/overlay',
          },
          {
            id: 'user-interface-angular-cdk-layout-positioning-portal',
            title: 'Portal',
            type: 'basic',
            icon: 'radio_button_checked',
            link: '/ui/cdk/portal',
          },
          {
            id: 'user-interface-angular-cdk-layout-positioning-scrolling',
            title: 'Scrolling',
            type: 'basic',
            icon: 'unfold_more',
            link: '/ui/cdk/scrolling',
          },
          {
            id: 'user-interface-angular-cdk-layout-positioning-virtual-scrolling',
            title: 'Virtual Scrolling',
            type: 'basic',
            icon: 'view_agenda',
            link: '/ui/cdk/virtual-scrolling',
          },
        ],
      },
      {
        id: 'user-interface-angular-cdk-interaction-behavior',
        title: 'Interaction & Behavior',
        type: 'collapsable',
        icon: 'pan_tool',
        children: [
          {
            id: 'user-interface-angular-cdk-interaction-behavior-drag-drop',
            title: 'Drag and Drop',
            type: 'basic',
            icon: 'open_with',
            link: '/ui/cdk/drag-drop',
          },
          {
            id: 'user-interface-angular-cdk-interaction-behavior-observers',
            title: 'Observers',
            type: 'basic',
            icon: 'visibility',
            link: '/ui/cdk/observers',
          },
          {
            id: 'user-interface-angular-cdk-interaction-behavior-platform',
            title: 'Platform',
            type: 'basic',
            icon: 'devices',
            link: '/ui/cdk/platform',
          },
          {
            id: 'user-interface-angular-cdk-interaction-behavior-stepper-cdk',
            title: 'Stepper',
            type: 'basic',
            icon: 'account_tree',
            link: '/ui/cdk/stepper',
          },
        ],
      },
      {
        id: 'user-interface-angular-cdk-forms-data',
        title: 'Forms & Data',
        type: 'collapsable',
        icon: 'storage',
        children: [
          {
            id: 'user-interface-angular-cdk-forms-data-accordion',
            title: 'Accordion',
            type: 'basic',
            icon: 'expand_more',
            link: '/ui/cdk/accordion',
          },
          {
            id: 'user-interface-angular-cdk-forms-data-table-cdk',
            title: 'Table',
            type: 'basic',
            icon: 'table_chart',
            link: '/ui/cdk/table',
          },
          {
            id: 'user-interface-angular-cdk-forms-data-tree-cdk',
            title: 'Tree',
            type: 'basic',
            icon: 'hub',
            link: '/ui/cdk/tree',
          },
        ],
      },
      {
        id: 'user-interface-angular-cdk-utilities-helpers',
        title: 'Utilities & Helpers',
        type: 'collapsable',
        icon: 'build',
        children: [
          {
            id: 'user-interface-angular-cdk-utilities-helpers-bidi',
            title: 'Bidirectionality',
            type: 'basic',
            icon: 'swap_horiz',
            link: '/ui/cdk/bidi',
          },
          {
            id: 'user-interface-angular-cdk-utilities-helpers-clipboard',
            title: 'Clipboard',
            type: 'basic',
            icon: 'content_paste',
            link: '/ui/cdk/clipboard',
          },
          {
            id: 'user-interface-angular-cdk-utilities-helpers-coercion',
            title: 'Coercion',
            type: 'basic',
            icon: 'shuffle',
            link: '/ui/cdk/coercion',
          },
          {
            id: 'user-interface-angular-cdk-utilities-helpers-collections',
            title: 'Collections',
            type: 'basic',
            icon: 'folder',
            link: '/ui/cdk/collections',
          },
          {
            id: 'user-interface-angular-cdk-utilities-helpers-keycodes',
            title: 'Keycodes',
            type: 'basic',
            icon: 'keyboard',
            link: '/ui/cdk/keycodes',
          },
        ],
      },
      {
        id: 'user-interface-angular-cdk-testing-tools',
        title: 'Testing Tools',
        type: 'collapsable',
        icon: 'bug_report',
        children: [
          {
            id: 'user-interface-angular-cdk-testing-tools-component-harnesses',
            title: 'Component Harnesses',
            type: 'basic',
            icon: 'science',
            link: '/ui/cdk/testing',
          },
          {
            id: 'user-interface-angular-cdk-testing-tools-test-harnesses',
            title: 'Test Harnesses',
            type: 'basic',
            icon: 'science',
            link: '/ui/cdk/test-harnesses',
          },
        ],
      },
      {
        id: 'user-interface-angular-cdk-advanced-feature',
        title: 'Advanced feature',
        type: 'collapsable',
        icon: 'settings',
        children: [
          {
            id: 'user-interface-angular-cdk-advanced-feature-dialog-cdk',
            title: 'Dialog',
            type: 'basic',
            icon: 'chat',
            link: '/ui/cdk/dialog',
          },
          {
            id: 'user-interface-angular-cdk-advanced-feature-text-field',
            title: 'Text Field',
            type: 'basic',
            icon: 'text_fields',
            link: '/ui/cdk/text-field',
          },
        ],
      },
    ],
  },
];
