import { NavigationItem } from '@ojiepermana/material/navigation';

export const DemoNavigationData: NavigationItem[] = [
  {
    id: 'documentation',
    title: 'Documentation',
    subtitle: 'Guides and getting started resources',
    type: 'group',
    icon: 'menu_book',
    children: [
      {
        id: 'documentation-introduction',
        title: 'Introduction',
        type: 'basic',
        icon: 'menu_book',
        link: '/docs/introduction',
      },
      {
        id: 'documentation-installation',
        title: 'Installation',
        type: 'basic',
        icon: 'download',
        link: '/docs/installation',
      },
      {
        id: 'documentation-getting-started',
        title: 'Getting started',
        type: 'basic',
        icon: 'rocket_launch',
        link: '/docs/getting-started',
      },
      {
        id: 'documentation-upgrade-guide',
        title: 'Upgrade Guide',
        type: 'basic',
        icon: 'arrow_circle_up',
        link: '/docs/upgrade-guide',
      },
      {
        id: 'documentation-changelog',
        title: 'Changelog',
        type: 'basic',
        icon: 'history',
        link: '/docs/changelog',
      },
      {
        id: 'documentation-icon-lucide',
        title: 'Lucide Icons',
        type: 'basic',
        icon: 'star',
        link: '/lucide-icons',
        badge: {
          title: 'Demo',
          classes: 'ml-2 px-2 py-0.5 rounded-full text-xs bg-blue-500 text-white',
        },
      },
    ],
  },
  {
    id: 'user-interface',
    title: 'User Interface',
    subtitle: 'Components and design elements',
    type: 'group',
    icon: 'dashboard',
    children: [
      {
        id: 'user-interface-component',
        title: 'Component',
        type: 'collapsable',
        icon: 'deployed_code',
        children: [
          {
            id: 'component-charts',
            title: 'Charts',
            type: 'basic',
            icon: 'monitoring',
            link: '/ui/chart',
            badge: {
              title: 'New',
              classes: 'ml-2 px-2 py-0.5 rounded-full text-xs bg-emerald-500 text-white',
            },
          },
          {
            id: 'shadcn-accordion',
            title: 'Accordion',
            type: 'basic',
            icon: 'expand_more',
            link: '/ui/shadcn/accordion',
          },
          { id: 'shadcn-alert', title: 'Alert', type: 'basic', icon: 'error_outline', link: '/ui/shadcn/alert' },
          { id: 'shadcn-avatar', title: 'Avatar', type: 'basic', icon: 'account_circle', link: '/ui/shadcn/avatar' },
          { id: 'shadcn-badge', title: 'Badge', type: 'basic', icon: 'verified', link: '/ui/shadcn/badge' },
          {
            id: 'shadcn-breadcrumb',
            title: 'Breadcrumb',
            type: 'basic',
            icon: 'more_horiz',
            link: '/ui/shadcn/breadcrumb',
          },
          { id: 'shadcn-button', title: 'Button', type: 'basic', icon: 'crop_square', link: '/ui/shadcn/button' },
          {
            id: 'shadcn-calendar',
            title: 'Calendar',
            type: 'basic',
            icon: 'calendar_month',
            link: '/ui/shadcn/calendar',
          },
          { id: 'shadcn-card', title: 'Card', type: 'basic', icon: 'credit_card', link: '/ui/shadcn/card' },
          { id: 'shadcn-checkbox', title: 'Checkbox', type: 'basic', icon: 'check_box', link: '/ui/shadcn/checkbox' },
          { id: 'shadcn-combobox', title: 'Combobox', type: 'basic', icon: 'search', link: '/ui/shadcn/combobox' },
          {
            id: 'shadcn-command',
            title: 'Command',
            type: 'basic',
            icon: 'keyboard_command_key',
            link: '/ui/shadcn/command',
          },
          {
            id: 'shadcn-context-menu',
            title: 'Context Menu',
            type: 'basic',
            icon: 'more_vert',
            link: '/ui/shadcn/context-menu',
          },
          {
            id: 'shadcn-date-picker',
            title: 'Date Picker',
            type: 'basic',
            icon: 'event',
            link: '/ui/shadcn/date-picker',
          },
          { id: 'shadcn-dialog', title: 'Dialog', type: 'basic', icon: 'chat', link: '/ui/shadcn/dialog' },
          {
            id: 'shadcn-dropdown-menu',
            title: 'Dropdown Menu',
            type: 'basic',
            icon: 'menu_open',
            link: '/ui/shadcn/dropdown-menu',
          },
          { id: 'shadcn-form', title: 'Form', type: 'basic', icon: 'description', link: '/ui/shadcn/form' },
          { id: 'shadcn-input', title: 'Input', type: 'basic', icon: 'text_fields', link: '/ui/shadcn/input' },
          { id: 'shadcn-label', title: 'Label', type: 'basic', icon: 'label', link: '/ui/shadcn/label' },
          {
            id: 'shadcn-pagination',
            title: 'Pagination',
            type: 'basic',
            icon: 'first_page',
            link: '/ui/shadcn/pagination',
          },
          { id: 'shadcn-popover', title: 'Popover', type: 'basic', icon: 'bubble_chart', link: '/ui/shadcn/popover' },
          {
            id: 'shadcn-progress',
            title: 'Progress',
            type: 'basic',
            icon: 'hourglass_empty',
            link: '/ui/shadcn/progress',
          },
          { id: 'shadcn-radio', title: 'Radio', type: 'basic', icon: 'radio_button_checked', link: '/ui/shadcn/radio' },
          {
            id: 'shadcn-scroll-area',
            title: 'Scroll Area',
            type: 'basic',
            icon: 'swap_vert',
            link: '/ui/shadcn/scroll-area',
          },
          { id: 'shadcn-select', title: 'Select', type: 'basic', icon: 'expand_more', link: '/ui/shadcn/select' },
          { id: 'shadcn-separator', title: 'Separator', type: 'basic', icon: 'remove', link: '/ui/shadcn/separator' },
          { id: 'shadcn-sheet', title: 'Sheet', type: 'basic', icon: 'view_sidebar', link: '/ui/shadcn/sheet' },
          { id: 'shadcn-skeleton', title: 'Skeleton', type: 'basic', icon: 'view_agenda', link: '/ui/shadcn/skeleton' },
          { id: 'shadcn-slider', title: 'Slider', type: 'basic', icon: 'tune', link: '/ui/shadcn/slider' },
          { id: 'shadcn-switch', title: 'Switch', type: 'basic', icon: 'toggle_on', link: '/ui/shadcn/switch' },
          { id: 'shadcn-table', title: 'Table', type: 'basic', icon: 'table_chart', link: '/ui/shadcn/table' },
          { id: 'shadcn-tabs', title: 'Tabs', type: 'basic', icon: 'tab', link: '/ui/shadcn/tabs' },
          { id: 'shadcn-textarea', title: 'Textarea', type: 'basic', icon: 'notes', link: '/ui/shadcn/textarea' },
          { id: 'shadcn-toast', title: 'Toast', type: 'basic', icon: 'notifications', link: '/ui/shadcn/toast' },
          { id: 'shadcn-tooltip', title: 'Tooltip', type: 'basic', icon: 'help', link: '/ui/shadcn/tooltip' },
        ],
      },
    ],
  },
  {
    id: 'feature',
    title: 'Features',
    subtitle: 'Advanced functionality and customization options',
    type: 'group',
    icon: 'settings',
    children: [
      {
        id: 'feature-theme',
        title: 'Themes',
        type: 'collapsable',
        icon: 'palette',
        children: [
          {
            id: 'feature-theme-dark-mode',
            title: 'Dark Mode',
            type: 'basic',
            icon: 'dark_mode',
            link: '/feature/theme/dark-mode',
          },
          {
            id: 'feature-theme-color',
            title: 'Color Schemes',
            type: 'basic',
            icon: 'palette',
            link: '/feature/theme/color-schemes',
            badge: {
              title: 'Beta',
              classes: 'ml-2 px-2 py-0.5 rounded-full text-xs bg-yellow-500 text-white',
            },
          },
          {
            id: 'feature-layout',
            title: 'Layout',
            type: 'collapsable',
            icon: 'dashboard',
            children: [
              {
                id: 'feature-layout-apps',
                title: 'Application',
                type: 'collapsable',
                icon: 'web',
                children: [
                  {
                    id: 'feature-layout-apps-vertical',
                    title: 'Vertical',
                    type: 'basic',
                    icon: 'view_sidebar',
                    link: '/feature/layout/application/vertical',
                  },
                  {
                    id: 'feature-layout-apps-horizontal',
                    title: 'Horizontal',
                    type: 'basic',
                    icon: 'view_column',
                    link: '/feature/layout/application/horizontal',
                  },
                ],
              },
              {
                id: 'feature-layout-page',
                title: 'Pages',
                type: 'collapsable',
                icon: 'description',
                children: [
                  {
                    id: 'feature-layout-page-page',
                    title: 'Page',
                    type: 'basic',
                    icon: 'description',
                    link: '/feature/layout/page/page',
                  },
                  {
                    id: 'feature-layout-page-content',
                    title: 'Content',
                    type: 'basic',
                    icon: 'description',
                    link: '/feature/layout/page/content',
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 'feature-navigation',
        title: 'Navigation',
        type: 'collapsable',
        icon: 'navigation',
        children: [
          {
            id: 'feature-navigation-horizontal-navigation',
            title: 'Horizontal ',
            type: 'basic',
            icon: 'view_column',
            link: '/feature/navigation/horizontal',
          },
          {
            id: 'feature-navigation-vertical-navigation',
            title: 'Vertical ',
            type: 'collapsable',
            icon: 'view_agenda',
            children: [
              {
                id: 'feature-navigation-vertical-navigation-default',
                title: 'Default',
                type: 'basic',
                icon: 'view_agenda',
                link: '/feature/navigation/vertical/default',
              },
              {
                id: 'feature-navigation-vertical-navigation-thin',
                title: 'Thin',
                type: 'basic',
                icon: 'view_agenda',
                link: '/feature/navigation/vertical/thin',
              },
              {
                id: 'feature-navigation-vertical-navigation-compact',
                title: 'Compact',
                type: 'basic',
                icon: 'view_agenda',
                link: '/feature/navigation/vertical/compact',
              },
              {
                id: 'feature-navigation-vertical-navigation-dense',
                title: 'Dense',
                type: 'basic',
                icon: 'view_agenda',
                link: '/feature/navigation/vertical/dense',
              },
            ],
          },
        ],
      },
    ],
  },
];
