import { existsSync, readFileSync } from 'node:fs';
import { dirname, isAbsolute, posix, relative, resolve } from 'node:path';

import type { ResolvedSdkTarget } from '../config/schema';
import type { SdkIR } from '../parser/types';
import { finalize, type VirtualFile } from '../render/template';

const ROOT_ENTRYPOINT = '';
const VIRTUAL_ROOT = '/__sdk__';

/**
 * No-op writer for the standalone mode — returns emitted files unchanged. Kept
 * as a named function so modes are composable from a single switch at the
 * engine layer.
 */
export function writeStandalone(files: VirtualFile[]): VirtualFile[] {
  return files;
}

/**
 * Library mode: add `ng-package.json`, `package.json`, and a top-level README
 * so the `output` folder can be built with ng-packagr directly.
 */
export function writeLibrary(
  files: VirtualFile[],
  ir: SdkIR,
  target: ResolvedSdkTarget,
  workspaceRoot: string,
  outputDir: string,
): VirtualFile[] {
  const normalizedFiles = rewriteCrossEntrypointImports(files, target, workspaceRoot, outputDir);
  const ngPackage = {
    $schema: toPosixPath(relative(outputDir, resolve(workspaceRoot, 'node_modules/ng-packagr/ng-package.schema.json'))),
    dest: toPosixPath(relative(outputDir, resolve(workspaceRoot, 'dist', packageSlug(target.packageName)))),
    lib: { entryFile: 'public-api.ts' },
  };

  const pkg = {
    name: target.packageName,
    version: target.packageVersion,
    description: `Generated SDK for ${ir.title} ${ir.version}`,
    peerDependencies: {
      '@angular/common': '>=21.2.0',
      '@angular/core': '>=21.2.0',
      rxjs: '>=7.8.0',
    },
    sideEffects: false,
  };

  return [
    ...normalizedFiles,
    createNgPackageFile('ng-package.json', ngPackage),
    ...createNestedEntrypointNgPackages(normalizedFiles),
    {
      path: 'package.json',
      content: finalize(JSON.stringify(pkg, null, 2)),
    },
    {
      path: 'README.md',
      content: finalize(
        `# ${target.packageName}\n\nGenerated SDK for **${ir.title}** v${ir.version}.\n\nThis folder was generated by the local SDK generator. Do not edit by hand.\n`,
      ),
    },
  ];
}

/**
 * Secondary-entrypoint mode: same file set as standalone, plus a minimal
 * `ng-package.json` pointing at `public-api.ts`. Meant to live **inside** an
 * existing library (e.g. `projects/angular/sdk-api/`) so ng-packagr picks it
 * up automatically as a secondary entrypoint of the parent library.
 */
export function writeSecondaryEntrypoint(
  files: VirtualFile[],
  _ir: SdkIR,
  target: ResolvedSdkTarget,
  workspaceRoot: string,
  outputDir: string,
): VirtualFile[] {
  const normalizedFiles = rewriteCrossEntrypointImports(files, target, workspaceRoot, outputDir);
  const ngPackage = {
    lib: { entryFile: 'public-api.ts' },
  };
  return [
    ...normalizedFiles,
    createNgPackageFile('ng-package.json', ngPackage),
    ...createNestedEntrypointNgPackages(normalizedFiles),
  ];
}

function rewriteCrossEntrypointImports(
  files: readonly VirtualFile[],
  target: ResolvedSdkTarget,
  workspaceRoot: string,
  outputDir: string,
): VirtualFile[] {
  const entrypointDirs = collectEntrypointDirs(files);
  if (entrypointDirs.length <= 1) {
    return [...files];
  }

  const packageImportBase = resolvePackageImportBase(target, workspaceRoot, outputDir);
  if (!packageImportBase) {
    return [...files];
  }

  const knownFiles = new Set(files.map((file) => file.path));

  return files.map((file) => {
    const owner = findEntrypointOwner(file.path, entrypointDirs);
    if (owner === ROOT_ENTRYPOINT) {
      return file;
    }

    return {
      ...file,
      content: file.content.replace(/(from\s+['"])([^'"]+)(['"])/g, (_match, prefix, spec, suffix) => {
        const nextSpec = rewriteModuleSpecifier(spec, file.path, owner, entrypointDirs, knownFiles, packageImportBase);
        return `${prefix}${nextSpec}${suffix}`;
      }),
    };
  });
}

function rewriteModuleSpecifier(
  specifier: string,
  currentPath: string,
  currentOwner: string,
  entrypointDirs: readonly string[],
  knownFiles: ReadonlySet<string>,
  packageImportBase: string,
): string {
  if (!specifier.startsWith('./') && !specifier.startsWith('../')) {
    return specifier;
  }

  const targetPath = resolveVirtualFilePath(currentPath, specifier, knownFiles);
  if (!targetPath) {
    return specifier;
  }

  const targetOwner = findEntrypointOwner(targetPath, entrypointDirs);
  if (targetOwner === currentOwner) {
    return specifier;
  }

  return buildEntrypointImport(packageImportBase, targetOwner);
}

function resolveVirtualFilePath(
  currentPath: string,
  specifier: string,
  knownFiles: ReadonlySet<string>,
): string | undefined {
  const currentAbs = posix.join(VIRTUAL_ROOT, currentPath);
  const resolved = posix.normalize(posix.join(dirname(currentAbs), specifier));
  const candidates = [`${resolved}.ts`, `${resolved}/index.ts`, `${resolved}/public-api.ts`, resolved];

  for (const candidate of candidates) {
    if (!candidate.startsWith(`${VIRTUAL_ROOT}/`)) {
      continue;
    }

    const relativePath = candidate.slice(VIRTUAL_ROOT.length + 1);
    if (knownFiles.has(relativePath)) {
      return relativePath;
    }
  }

  return undefined;
}

function resolvePackageImportBase(target: ResolvedSdkTarget, workspaceRoot: string, outputDir: string): string {
  if (target.mode === 'library') {
    return target.packageName;
  }

  if (target.mode !== 'secondary-entrypoint') {
    return '';
  }

  return inferSecondaryEntrypointPackageName(workspaceRoot, outputDir, target.packageName);
}

function inferSecondaryEntrypointPackageName(workspaceRoot: string, outputDir: string, fallback: string): string {
  let currentDir = outputDir;
  let nearestPackageDir: string | undefined;
  let nearestPackagrDir: string | undefined;

  while (isWithinWorkspace(currentDir, workspaceRoot)) {
    const packageJsonPath = resolve(currentDir, 'package.json');
    if (existsSync(packageJsonPath)) {
      nearestPackageDir ??= currentDir;
      if (existsSync(resolve(currentDir, 'ng-package.json'))) {
        nearestPackagrDir = currentDir;
        break;
      }
    }

    if (currentDir === workspaceRoot) {
      break;
    }

    const parentDir = dirname(currentDir);
    if (parentDir === currentDir) {
      break;
    }

    currentDir = parentDir;
  }

  const packageDir = nearestPackagrDir ?? nearestPackageDir;
  if (!packageDir) {
    return fallback;
  }

  const packageName = readPackageName(packageDir);
  if (!packageName) {
    return fallback;
  }

  const relativeOutput = toPosixPath(relative(packageDir, outputDir)).replace(/^\.\//, '');
  if (!relativeOutput || relativeOutput === '.') {
    return packageName;
  }

  return `${packageName}/${relativeOutput}`;
}

function readPackageName(packageDir: string): string | undefined {
  const packageJsonPath = resolve(packageDir, 'package.json');
  if (!existsSync(packageJsonPath)) {
    return undefined;
  }

  const raw = JSON.parse(readFileSync(packageJsonPath, 'utf8')) as { name?: unknown };
  return typeof raw.name === 'string' && raw.name.length > 0 ? raw.name : undefined;
}

function isWithinWorkspace(candidate: string, workspaceRoot: string): boolean {
  const rel = relative(workspaceRoot, candidate);
  return rel === '' || (!rel.startsWith('..') && !isAbsolute(rel));
}

function collectEntrypointDirs(files: readonly VirtualFile[]): string[] {
  const dirs = new Set<string>();
  for (const file of files) {
    if (file.path === 'public-api.ts') {
      dirs.add(ROOT_ENTRYPOINT);
      continue;
    }

    if (!file.path.endsWith('/public-api.ts')) {
      continue;
    }

    dirs.add(file.path.slice(0, -'/public-api.ts'.length));
  }

  return [...dirs].sort((left, right) => right.length - left.length || left.localeCompare(right));
}

function findEntrypointOwner(filePath: string, entrypointDirs: readonly string[]): string {
  for (const entrypointDir of entrypointDirs) {
    if (entrypointDir === ROOT_ENTRYPOINT) {
      continue;
    }

    if (filePath === `${entrypointDir}/public-api.ts` || filePath.startsWith(`${entrypointDir}/`)) {
      return entrypointDir;
    }
  }

  return ROOT_ENTRYPOINT;
}

function buildEntrypointImport(packageImportBase: string, entrypointDir: string): string {
  return entrypointDir ? `${packageImportBase}/${entrypointDir}` : packageImportBase;
}

function createNestedEntrypointNgPackages(files: readonly VirtualFile[]): VirtualFile[] {
  return collectSecondaryEntrypointDirs(files).map((dir) =>
    createNgPackageFile(`${dir}/ng-package.json`, {
      lib: { entryFile: 'public-api.ts' },
    }),
  );
}

function collectSecondaryEntrypointDirs(files: readonly VirtualFile[]): string[] {
  const dirs = new Set<string>();
  for (const file of files) {
    if (!file.path.endsWith('/public-api.ts')) {
      continue;
    }

    dirs.add(file.path.slice(0, -'/public-api.ts'.length));
  }

  return [...dirs].sort();
}

function packageSlug(packageName: string): string {
  return packageName.replace(/^@/, '').replace(/\//g, '-');
}

function toPosixPath(value: string): string {
  return value.split('\\').join('/');
}

function createNgPackageFile(path: string, content: object): VirtualFile {
  return {
    path,
    content: finalize(JSON.stringify(content, null, 2)),
  };
}
