import type { ResolvedSdkTarget } from '../config/schema';
import type { SdkIR } from '../parser/types';
import { finalize, type VirtualFile } from '../render/template';

/**
 * No-op writer for the standalone mode — returns emitted files unchanged. Kept
 * as a named function so modes are composable from a single switch at the
 * engine layer.
 */
export function writeStandalone(files: VirtualFile[]): VirtualFile[] {
  return files;
}

/**
 * Library mode: add `ng-package.json`, `package.json`, and a top-level README
 * so the `output` folder can be built with ng-packagr directly.
 */
export function writeLibrary(files: VirtualFile[], ir: SdkIR, target: ResolvedSdkTarget): VirtualFile[] {
  const ngPackage = {
    $schema: '../../node_modules/ng-packagr/ng-package.schema.json',
    dest: `../dist/${target.packageName.replace(/^@/, '').replace(/\//g, '-')}`,
    lib: { entryFile: 'public-api.ts' },
  };

  const pkg = {
    name: target.packageName,
    version: target.packageVersion,
    description: `Generated SDK for ${ir.title} ${ir.version}`,
    peerDependencies: {
      '@angular/common': '>=20.0.0',
      '@angular/core': '>=20.0.0',
      rxjs: '>=7.0.0',
    },
    sideEffects: false,
  };

  return [
    ...files,
    {
      path: 'ng-package.json',
      content: finalize(JSON.stringify(ngPackage, null, 2)),
    },
    {
      path: 'package.json',
      content: finalize(JSON.stringify(pkg, null, 2)),
    },
    {
      path: 'README.md',
      content: finalize(
        `# ${target.packageName}\n\nGenerated SDK for **${ir.title}** v${ir.version}.\n\nThis folder was generated by the local SDK generator. Do not edit by hand.\n`,
      ),
    },
  ];
}

/**
 * Secondary-entrypoint mode: same file set as standalone, plus a minimal
 * `ng-package.json` pointing at `public-api.ts`. Meant to live **inside** an
 * existing library (e.g. `projects/angular/sdk-api/`) so ng-packagr picks it
 * up automatically as a secondary entrypoint of the parent library.
 */
export function writeSecondaryEntrypoint(files: VirtualFile[], _ir: SdkIR, _target: ResolvedSdkTarget): VirtualFile[] {
  const ngPackage = {
    lib: { entryFile: 'public-api.ts' },
  };
  return [
    ...files,
    {
      path: 'ng-package.json',
      content: finalize(JSON.stringify(ngPackage, null, 2)),
    },
  ];
}
