/**
 * Public config shape for the SDK generator.
 *
 * Users place an `sdk.config.json` at the workspace root describing one or more
 * generation targets. All paths are resolved relative to the workspace root
 * (i.e. the directory containing the config file).
 */

export type SdkOutputMode = 'standalone' | 'library' | 'secondary-entrypoint';

export interface SdkFeatureFlags {
  /** Emit `models/*.ts` (type-only DTO interfaces). Default `true`. */
  models?: boolean;
  /** Emit tree-shakeable operation functions in `fn/<tag>/*.ts`. Default `true`. */
  operations?: boolean;
  /** Emit grouped Injectable service classes per tag. Default `true`. */
  services?: boolean;
  /** Emit the runtime client primitives (ApiConfiguration, BaseService, etc). Default `true`. */
  client?: boolean;
  /** Emit operation rules + field validators + permission helpers. Default `true`. */
  metadata?: boolean;
  /** Emit navigation tree derived from tags (parent, x-icon). Default `false`. */
  navigation?: boolean;
}

export interface SdkTargetConfig {
  /** Path to OpenAPI 3.x spec (YAML or JSON). Required. */
  input: string;
  /** Output directory (relative to workspace root). Required. */
  output: string;
  /** Output mode. Defaults to `"standalone"`. */
  mode?: SdkOutputMode;
  /** Optional human-readable name used for logs & the generated `Api` class. */
  clientName?: string;
  /** Package name used when `mode === "library"`. */
  packageName?: string;
  /** Package version used when `mode === "library"`. Defaults to `0.0.1`. */
  packageVersion?: string;
  /** Default rootUrl baked into ApiConfiguration. Defaults to the first server in the spec. */
  rootUrl?: string;
  /** Feature toggles. Every feature defaults to `true` except `navigation` (default `true` too). */
  features?: SdkFeatureFlags;
  /** Custom file banner. Defaults to a short auto-generated notice. */
  banner?: string;
}

export interface SdkConfig {
  targets: SdkTargetConfig[];
}

export interface ResolvedFeatureFlags {
  models: boolean;
  operations: boolean;
  services: boolean;
  client: boolean;
  metadata: boolean;
  navigation: boolean;
}

export interface ResolvedSdkTarget {
  input: string;
  output: string;
  mode: SdkOutputMode;
  clientName: string;
  packageName: string;
  packageVersion: string;
  rootUrl: string | undefined;
  features: ResolvedFeatureFlags;
  banner: string;
}

const DEFAULT_BANNER = '/* eslint-disable */\n/* Auto-generated by @ojiepermana/sdk-generator. DO NOT EDIT. */';

const DEFAULT_FEATURES: ResolvedFeatureFlags = {
  models: true,
  operations: true,
  services: true,
  client: true,
  metadata: true,
  navigation: true,
};

export function resolveTarget(raw: SdkTargetConfig): ResolvedSdkTarget {
  if (!raw || typeof raw !== 'object') {
    throw new Error('Invalid target: expected object');
  }
  if (!raw.input) throw new Error('Target is missing required "input"');
  if (!raw.output) throw new Error('Target is missing required "output"');

  const mode: SdkOutputMode = raw.mode ?? 'standalone';
  if (!['standalone', 'library', 'secondary-entrypoint'].includes(mode)) {
    throw new Error(`Invalid target mode: ${mode}`);
  }

  return {
    input: raw.input,
    output: raw.output,
    mode,
    clientName: raw.clientName ?? 'Api',
    packageName: raw.packageName ?? '@local/sdk',
    packageVersion: raw.packageVersion ?? '0.0.1',
    rootUrl: raw.rootUrl,
    features: { ...DEFAULT_FEATURES, ...(raw.features ?? {}) },
    banner: raw.banner ?? DEFAULT_BANNER,
  };
}

export function resolveConfig(raw: unknown): ResolvedSdkTarget[] {
  if (!raw || typeof raw !== 'object') {
    throw new Error('Invalid SDK config: root must be an object');
  }
  const cfg = raw as SdkConfig;
  if (!Array.isArray(cfg.targets) || cfg.targets.length === 0) {
    throw new Error('Invalid SDK config: "targets" must be a non-empty array');
  }
  return cfg.targets.map(resolveTarget);
}
