import type { ComponentStyle, ResolvedGuideConfig } from '../config/schema';
import type { Frontmatter } from './frontmatter';
import { componentClassName, componentFileBase, componentSelector, toSlug } from './naming';
import { escapeForTemplateLiteral, renderMarkdown } from './render';

export interface GeneratedComponent {
  /** Component class name, e.g. `DocIntroOverviewComponent`. */
  readonly className: string;
  /** Selector used in the generated `@Component`. */
  readonly selector: string;
  /** Component .ts file contents. */
  readonly tsContent: string;
  /** Optional stylesheet file (css/scss) contents, or `null` when `componentStyle` is `'none'`. */
  readonly styleContent: string | null;
  /** Path relative to `outputDir` for the .ts file, e.g. `intro/overview.component.ts`. */
  readonly tsPath: string;
  /** Path relative to `outputDir` for the stylesheet, or `null` when not emitted. */
  readonly stylePath: string | null;
  /** The route URL segment (single folder level) this component lives under. */
  readonly segments: readonly string[];
  /** Title for route data. */
  readonly title: string;
  /** Order for route data (optional). */
  readonly order: number | null;
  /** Route path override from frontmatter if any. */
  readonly pathOverride: string | null;
}

export function buildComponent(
  segments: readonly string[],
  frontmatter: Frontmatter,
  body: string,
  config: ResolvedGuideConfig,
): GeneratedComponent {
  const html = renderMarkdown(body);
  const escaped = escapeForTemplateLiteral(html);

  const className = componentClassName(config.componentPrefix, segments);
  const selector = componentSelector(config.componentPrefix, segments);
  const fileBase = componentFileBase(segments);
  const folderPath = segments.slice(0, -1).map(toSlug).join('/');

  const tsPath = joinPath(folderPath, `${fileBase}.component.ts`);
  const { stylePath, styleRef, styleContent } = styleAssets(config.componentStyle, folderPath, fileBase);

  const title =
    typeof frontmatter.title === 'string' && frontmatter.title.trim()
      ? frontmatter.title.trim()
      : humanizeTitle(segments);
  const order = typeof frontmatter.order === 'number' ? frontmatter.order : null;
  const pathOverride = typeof frontmatter.path === 'string' && frontmatter.path.trim() ? frontmatter.path.trim() : null;

  const tsContent = renderComponentTs({
    className,
    selector,
    html: escaped,
    styleRef,
  });

  return {
    className,
    selector,
    tsContent,
    styleContent,
    tsPath,
    stylePath,
    segments,
    title,
    order,
    pathOverride,
  };
}

interface StyleAssets {
  stylePath: string | null;
  styleRef: string | null;
  styleContent: string | null;
}

function styleAssets(style: ComponentStyle, folder: string, fileBase: string): StyleAssets {
  if (style === 'none') {
    return { stylePath: null, styleRef: null, styleContent: null };
  }
  const ext = style === 'scss' ? 'scss' : 'css';
  const stylePath = joinPath(folder, `${fileBase}.component.${ext}`);
  return {
    stylePath,
    styleRef: `./${fileBase}.component.${ext}`,
    styleContent: `:host { display: block; }\n`,
  };
}

interface RenderTsOptions {
  className: string;
  selector: string;
  html: string;
  styleRef: string | null;
}

function renderComponentTs(opts: RenderTsOptions): string {
  const styleLine = opts.styleRef ? `  styleUrl: '${opts.styleRef}',\n` : '';
  return (
    `// Auto-generated by @ojiepermana/angular/generator/guide. Do not edit by hand.\n` +
    `import { ChangeDetectionStrategy, Component } from '@angular/core';\n\n` +
    `@Component({\n` +
    `  selector: '${opts.selector}',\n` +
    `  changeDetection: ChangeDetectionStrategy.OnPush,\n` +
    styleLine +
    `  template: \`${opts.html}\`,\n` +
    `})\n` +
    `export class ${opts.className} {}\n`
  );
}

function humanizeTitle(segments: readonly string[]): string {
  const last = segments[segments.length - 1] ?? 'Untitled';
  return last
    .replace(/[-_]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/(^|\s)\S/g, (c) => c.toUpperCase());
}

function joinPath(folder: string, file: string): string {
  return folder ? `${folder}/${file}` : file;
}
