import type { ResolvedGuideConfig } from '../config/schema';
import type { GeneratedComponent } from './component';
import { toSlug } from './naming';

interface RouteNode {
  segment: string;
  children: Map<string, RouteNode>;
  leaf?: GeneratedComponent;
}

export function renderRoutes(components: readonly GeneratedComponent[], config: ResolvedGuideConfig): string {
  const root: RouteNode = { segment: '', children: new Map() };
  for (const comp of components) {
    insert(root, comp);
  }
  const body = serializeChildren(root, '  ');
  const exportName = config.routeExportName;
  return (
    `// Auto-generated by @ojiepermana/angular/generator/guide. Do not edit by hand.\n` +
    `import type { Routes } from '@angular/router';\n\n` +
    `export const ${exportName}: Routes = [\n` +
    body +
    `];\n`
  );
}

function insert(root: RouteNode, comp: GeneratedComponent): void {
  const segments = routeSegments(comp);
  let node = root;
  for (let i = 0; i < segments.length - 1; i++) {
    const seg = segments[i];
    let next = node.children.get(seg);
    if (!next) {
      next = { segment: seg, children: new Map() };
      node.children.set(seg, next);
    }
    node = next;
  }
  const leafSeg = segments[segments.length - 1];
  let leaf = node.children.get(leafSeg);
  if (!leaf) {
    leaf = { segment: leafSeg, children: new Map() };
    node.children.set(leafSeg, leaf);
  }
  if (leaf.leaf) {
    throw new Error(
      `[guide] Route conflict: two markdown files resolve to the same path "${segments.join('/') || '<root>'}".`,
    );
  }
  leaf.leaf = comp;
}

function routeSegments(comp: GeneratedComponent): string[] {
  // file segments without extension; handle index.md as empty path at parent level
  const segs = comp.segments.slice();
  const last = segs[segs.length - 1] ?? 'index';
  if (comp.pathOverride !== null) {
    // Override replaces the leaf segment path (keeps parent folders).
    segs[segs.length - 1] = comp.pathOverride === '' ? '' : comp.pathOverride;
  } else if (/^index$/i.test(last)) {
    segs[segs.length - 1] = '';
  } else {
    segs[segs.length - 1] = toSlug(last);
  }
  // slugify folder segments
  for (let i = 0; i < segs.length - 1; i++) {
    segs[i] = toSlug(segs[i]);
  }
  return segs;
}

function serializeChildren(node: RouteNode, indent: string): string {
  const children = [...node.children.values()].sort(compareNodes);
  return children.map((c) => serializeNode(c, indent)).join('');
}

function compareNodes(a: RouteNode, b: RouteNode): number {
  const orderA = a.leaf?.order ?? Number.POSITIVE_INFINITY;
  const orderB = b.leaf?.order ?? Number.POSITIVE_INFINITY;
  if (orderA !== orderB) return orderA - orderB;
  return a.segment.localeCompare(b.segment);
}

function serializeNode(node: RouteNode, indent: string): string {
  const next = indent + '  ';
  const lines: string[] = [];
  lines.push(`${indent}{`);
  lines.push(`${next}path: ${JSON.stringify(node.segment)},`);

  if (node.leaf) {
    const comp = node.leaf;
    const importPath = importSpecifier(comp.tsPath);
    lines.push(`${next}loadComponent: () => import(${JSON.stringify(importPath)}).then((m) => m.${comp.className}),`);
    const data = routeData(comp);
    if (data) lines.push(`${next}data: ${data},`);
  }

  if (node.children.size > 0) {
    lines.push(`${next}children: [`);
    lines.push(serializeChildren(node, next + '  ').replace(/\n+$/, ''));
    lines.push(`${next}],`);
  }

  lines.push(`${indent}},`);
  return lines.join('\n') + '\n';
}

function routeData(comp: GeneratedComponent): string | null {
  const parts: string[] = [];
  if (comp.title) parts.push(`title: ${JSON.stringify(comp.title)}`);
  if (comp.order !== null) parts.push(`order: ${comp.order}`);
  if (parts.length === 0) return null;
  return `{ ${parts.join(', ')} }`;
}

function importSpecifier(tsPath: string): string {
  const noExt = tsPath.replace(/\.ts$/i, '');
  return `./${noExt}`;
}
